test_that("workflow-template-check.yaml is included in manifest", {
  # Try to find manifest file in different locations
  manifest_path <- system.file(
    "gha_templates/gha_version.json",
    package = "gsm.utils"
  )
  if (!file.exists(manifest_path) || manifest_path == "") {
    manifest_path <- file.path(
      find.package("gsm.utils", quiet = TRUE),
      "inst",
      "gha_templates",
      "gha_version.json"
    )
  }
  if (!file.exists(manifest_path)) {
    manifest_path <- "../../inst/gha_templates/gha_version.json" # relative from testthat folder
  }
  if (!file.exists(manifest_path)) {
    skip("Cannot find manifest file for testing")
  }

  manifest <- jsonlite::fromJSON(manifest_path, simplifyVector = TRUE)
  workflow_names <- manifest$workflows$name

  expect_true("workflow-template-check.yaml" %in% workflow_names)

  # Check that the workflow has proper description
  workflow_entry <- manifest$workflows[
    manifest$workflows$name == "workflow-template-check.yaml",
  ]
  expect_true(nrow(workflow_entry) == 1)
  expect_true(grepl(
    "Check if GitHub Actions workflows match gsm.utils templates",
    workflow_entry$description
  ))
})

test_that("workflow-template-check.yaml template file exists", {
  # Try to find template file in different locations
  template_path <- system.file(
    "gha_templates/workflows/workflow-template-check.yaml",
    package = "gsm.utils"
  )
  if (!file.exists(template_path) || template_path == "") {
    template_path <- file.path(
      find.package("gsm.utils", quiet = TRUE),
      "inst",
      "gha_templates",
      "workflows",
      "workflow-template-check.yaml"
    )
  }
  if (!file.exists(template_path)) {
    template_path <- "../../inst/gha_templates/workflows/workflow-template-check.yaml" # relative from testthat folder
  }
  if (!file.exists(template_path)) {
    skip("Cannot find template file for testing")
  }

  # Check that the file has proper headers
  lines <- readLines(template_path, n = 5, warn = FALSE)

  expect_true(any(grepl("^# gsm.utils GHA version:", lines)))
  expect_true(any(grepl("^# Generated by:", lines)))
  expect_true(any(grepl("^# Description:", lines)))
})

test_that("workflow template check has correct triggers", {
  # Try to find template file in different locations
  template_path <- system.file(
    "gha_templates/workflows/workflow-template-check.yaml",
    package = "gsm.utils"
  )
  if (!file.exists(template_path) || template_path == "") {
    template_path <- file.path(
      find.package("gsm.utils", quiet = TRUE),
      "inst",
      "gha_templates",
      "workflows",
      "workflow-template-check.yaml"
    )
  }
  if (!file.exists(template_path)) {
    template_path <- "../../inst/gha_templates/workflows/workflow-template-check.yaml" # relative from testthat folder
  }
  if (!file.exists(template_path)) {
    skip("Cannot find template file for testing")
  }

  content <- readLines(template_path, warn = FALSE)

  # Should trigger on push to main/release
  expect_true(any(grepl("branches: \\[main, release\\]", content)))

  # Should also trigger on pull_request
  expect_true(any(grepl("pull_request:", content)))
})

test_that("check_workflow_compliance works with no workflows directory", {
  # Create temp directory without workflows
  temp_dir <- tempdir()
  temp_pkg <- file.path(temp_dir, "test_pkg_no_workflows_compliance")
  dir.create(temp_pkg, showWarnings = FALSE, recursive = TRUE)

  # Check compliance (should not fail on errors for this test)
  result <- check_workflow_compliance(
    temp_pkg,
    bVerbose = FALSE,
    bFailOnErrors = FALSE
  )

  expect_type(result, "list")
  expect_false(result$is_compliant)
  expect_gt(length(result$missing_workflows), 0)
  expect_equal(length(result$extra_workflows), 0)

  # Clean up
  unlink(temp_pkg, recursive = TRUE)
})

test_that("check_workflow_compliance detects compliant workflows", {
  # Create temp directory and install workflows
  temp_dir <- tempdir()
  temp_pkg <- file.path(temp_dir, "test_pkg_compliant_workflows")
  dir.create(temp_pkg, showWarnings = FALSE, recursive = TRUE)
  on.exit(unlink(temp_pkg, recursive = TRUE), add = TRUE)

  # Install workflows
  add_gsm_actions(temp_pkg) |>
    expect_message("Installing gsm\\.utils GitHub Actions") |>
    expect_message("Installed [0-9]+ workflow file[s]? to")

  # Check compliance
  result <- check_workflow_compliance(
    temp_pkg,
    bVerbose = FALSE,
    bFailOnErrors = FALSE
  )

  expect_type(result, "list")
  expect_true(result$is_compliant)
  expect_equal(length(result$missing_workflows), 0)
  expect_equal(length(result$version_issues), 0)
})

test_that("check_workflow_compliance detects missing or incorrect version header", {
  temp_dir <- tempdir()
  temp_pkg <- file.path(temp_dir, "test_pkg_bad_version_header")
  dir.create(temp_pkg, showWarnings = FALSE, recursive = TRUE)
  add_gsm_actions(temp_pkg) |>
    expect_message("Installing gsm\\.utils GitHub Actions") |>
    expect_message("Installed [0-9]+ workflow file[s]? to")

  workflows_dir <- file.path(temp_pkg, ".github", "workflows")

  # Corrupt the version header in R-CMD-check.yaml
  target <- file.path(workflows_dir, "R-CMD-check.yaml")
  lines <- readLines(target, warn = FALSE)
  lines[grep("^# gsm.utils GHA version:", lines)[
    1
  ]] <- "# gsm.utils GHA version: 0.0.0-bad"
  writeLines(lines, target)

  result <- check_workflow_compliance(
    temp_pkg,
    bVerbose = FALSE,
    bFailOnErrors = FALSE
  )

  expect_type(result, "list")
  # version_issues should flag the bad header
  expect_gt(length(result$version_issues), 0)
  expect_true(any(grepl("R-CMD-check.yaml", result$version_issues)))

  unlink(temp_pkg, recursive = TRUE)
})

test_that("check_workflow_compliance detects extra workflow files", {
  temp_dir <- tempdir()
  temp_pkg <- file.path(temp_dir, "test_pkg_extra_workflow")
  dir.create(temp_pkg, showWarnings = FALSE, recursive = TRUE)
  add_gsm_actions(temp_pkg) |>
    expect_message("Installing gsm\\.utils GitHub Actions") |>
    expect_message("Installed [0-9]+ workflow file[s]? to")

  # Add a workflow file that is not in the manifest
  extra_file <- file.path(
    temp_pkg,
    ".github",
    "workflows",
    "custom-deploy.yaml"
  )
  writeLines(c("# custom workflow", "on: push", "jobs:"), extra_file)

  result <- check_workflow_compliance(
    temp_pkg,
    bVerbose = FALSE,
    bFailOnErrors = FALSE
  )

  expect_type(result, "list")
  expect_true("custom-deploy.yaml" %in% result$extra_workflows)

  unlink(temp_pkg, recursive = TRUE)
})

test_that("check_workflow_compliance detects content differences in critical workflows", {
  temp_dir <- tempdir()
  temp_pkg <- file.path(temp_dir, "test_pkg_content_diff")
  dir.create(temp_pkg, showWarnings = FALSE, recursive = TRUE)
  add_gsm_actions(temp_pkg) |>
    expect_message("Installing gsm\\.utils GitHub Actions") |>
    expect_message("Installed [0-9]+ workflow file[s]? to")

  workflows_dir <- file.path(temp_pkg, ".github", "workflows")

  # Modify a non-comment line in R-CMD-check.yaml to introduce a content difference
  target <- file.path(workflows_dir, "R-CMD-check.yaml")
  lines <- readLines(target, warn = FALSE)
  # Replace the first non-comment, non-empty line with altered content
  non_comment_idx <- which(!grepl("^#|^\\s*$", lines))[1]
  lines[non_comment_idx] <- paste0(lines[non_comment_idx], " # modified")
  writeLines(lines, target)

  result <- check_workflow_compliance(
    temp_pkg,
    bVerbose = FALSE,
    bFailOnErrors = FALSE
  )

  expect_type(result, "list")
  expect_gt(length(result$content_issues), 0)
  expect_true(any(grepl("R-CMD-check.yaml", result$content_issues)))

  unlink(temp_pkg, recursive = TRUE)
})
