test_that("workflow-template-check.yaml is included in manifest", {
  # Try to find manifest file in different locations
  manifest_path <- system.file("gha_templates/gha_version.json", package = "gsm.utils")
  if (!file.exists(manifest_path) || manifest_path == "") {
    manifest_path <- file.path(find.package("gsm.utils", quiet = TRUE), "inst", "gha_templates", "gha_version.json")
  }
  if (!file.exists(manifest_path)) {
    manifest_path <- "../../inst/gha_templates/gha_version.json"  # relative from testthat folder
  }
  if (!file.exists(manifest_path)) {
    skip("Cannot find manifest file for testing")
  }
  
  manifest <- jsonlite::fromJSON(manifest_path, simplifyVector = TRUE)
  workflow_names <- manifest$workflows$name
  
  expect_true("workflow-template-check.yaml" %in% workflow_names)
  
  # Check that the workflow has proper description
  workflow_entry <- manifest$workflows[manifest$workflows$name == "workflow-template-check.yaml", ]
  expect_true(nrow(workflow_entry) == 1)
  expect_true(grepl("Check if GitHub Actions workflows match gsm.utils templates", workflow_entry$description))
})

test_that("workflow-template-check.yaml template file exists", {
  # Try to find template file in different locations
  template_path <- system.file("gha_templates/workflows/workflow-template-check.yaml", package = "gsm.utils")
  if (!file.exists(template_path) || template_path == "") {
    template_path <- file.path(find.package("gsm.utils", quiet = TRUE), "inst", "gha_templates", "workflows", "workflow-template-check.yaml")
  }
  if (!file.exists(template_path)) {
    template_path <- "../../inst/gha_templates/workflows/workflow-template-check.yaml"  # relative from testthat folder
  }
  if (!file.exists(template_path)) {
    skip("Cannot find template file for testing")
  }
  
  # Check that the file has proper headers
  lines <- readLines(template_path, n = 5, warn = FALSE)
  
  expect_true(any(grepl("^# gsm.utils GHA version:", lines)))
  expect_true(any(grepl("^# Generated by:", lines)))
  expect_true(any(grepl("^# Description:", lines)))
})

test_that("workflow template check has correct triggers", {
  # Try to find template file in different locations
  template_path <- system.file("gha_templates/workflows/workflow-template-check.yaml", package = "gsm.utils")
  if (!file.exists(template_path) || template_path == "") {
    template_path <- file.path(find.package("gsm.utils", quiet = TRUE), "inst", "gha_templates", "workflows", "workflow-template-check.yaml")
  }
  if (!file.exists(template_path)) {
    template_path <- "../../inst/gha_templates/workflows/workflow-template-check.yaml"  # relative from testthat folder
  }
  if (!file.exists(template_path)) {
    skip("Cannot find template file for testing")
  }
  
  content <- readLines(template_path, warn = FALSE)
  
  # Should trigger on push to main/release
  expect_true(any(grepl("branches: \\[main, release\\]", content)))
  
  # Should also trigger on pull_request
  expect_true(any(grepl("pull_request:", content)))
})

test_that("check_workflow_compliance function exists and has correct signature", {
  # Skip if function not available (in case package not loaded)
  skip_if_not(exists("check_workflow_compliance"))
  
  # Check function parameters (using formals)
  fn_args <- names(formals(check_workflow_compliance))
  expect_true("strPackageDir" %in% fn_args)
  expect_true("bVerbose" %in% fn_args)
  expect_true("bFailOnErrors" %in% fn_args)
})

test_that("check_workflow_compliance works with no workflows directory", {
  # Skip if function not available
  skip_if_not(exists("check_workflow_compliance"))
  
  # Create temp directory without workflows
  temp_dir <- tempdir()
  temp_pkg <- file.path(temp_dir, "test_pkg_no_workflows_compliance")
  dir.create(temp_pkg, showWarnings = FALSE, recursive = TRUE)
  
  # Check compliance (should not fail on errors for this test)
  result <- check_workflow_compliance(temp_pkg, bVerbose = FALSE, bFailOnErrors = FALSE)
  
  expect_type(result, "list")
  expect_false(result$is_compliant)
  expect_gt(length(result$missing_workflows), 0)
  expect_equal(length(result$extra_workflows), 0)
  
  # Clean up
  unlink(temp_pkg, recursive = TRUE)
})

test_that("check_workflow_compliance detects compliant workflows", {
  # Skip if functions not available
  skip_if_not(exists("check_workflow_compliance"))
  skip_if_not(exists("add_gsm_actions"))
  
  # Create temp directory and install workflows
  temp_dir <- tempdir()
  temp_pkg <- file.path(temp_dir, "test_pkg_compliant_workflows")
  dir.create(temp_pkg, showWarnings = FALSE, recursive = TRUE)
  
  # Install workflows
  add_gsm_actions(temp_pkg)
  
  # Check compliance
  result <- check_workflow_compliance(temp_pkg, bVerbose = FALSE, bFailOnErrors = FALSE)
  
  expect_type(result, "list")
  expect_true(result$is_compliant)
  expect_equal(length(result$missing_workflows), 0)
  expect_equal(length(result$version_issues), 0)
  
  # Clean up
  unlink(temp_pkg, recursive = TRUE)
})