test_that("check_gha_version works with no workflows", {
  # Create temp directory without workflows
  temp_dir <- tempdir()
  temp_pkg <- file.path(temp_dir, "test_pkg_no_workflows")
  dir.create(temp_pkg, showWarnings = FALSE)

  result <- check_gha_version(temp_pkg, bVerbose = FALSE)

  expect_type(result, "list")
  expect_true(is.na(result$package_version))
  expect_false(result$is_current)
  expect_equal(length(result$workflows_found), 0)
  expect_gt(length(result$workflows_missing), 0)

  # Clean up
  unlink(temp_pkg, recursive = TRUE)
})

test_that("check_gha_version detects current version", {
  # Create temp directory and install workflows
  temp_dir <- tempdir()
  temp_pkg <- file.path(temp_dir, "test_pkg_with_workflows")
  dir.create(temp_pkg, showWarnings = FALSE)

  # Install workflows
  add_gsm_actions(temp_pkg)

  result <- check_gha_version(temp_pkg, bVerbose = FALSE)

  expect_type(result, "list")
  expect_false(is.na(result$package_version))
  expect_equal(result$package_version, result$gsm_utils_version)
  expect_true(result$is_current)
  expect_gt(length(result$workflows_found), 0)

  # Clean up
  unlink(temp_pkg, recursive = TRUE)
})

test_that("check_gha_version detects outdated version", {
  # Create temp directory with old version
  temp_dir <- tempdir()
  temp_pkg <- file.path(temp_dir, "test_pkg_outdated")
  workflows_dir <- file.path(temp_pkg, ".github", "workflows")
  dir.create(workflows_dir, recursive = TRUE, showWarnings = FALSE)

  # Create a workflow with old version
  writeLines(
    c(
      "# gsm.utils GHA version: 0.1.0",
      "# Generated by: https://github.com/Gilead-BioStats/gsm.utils",
      "name: Test Workflow",
      "on: push"
    ),
    file.path(workflows_dir, "test.yaml")
  )

  result <- check_gha_version(temp_pkg, bVerbose = FALSE)

  expect_type(result, "list")
  expect_equal(result$package_version, "0.1.0")
  expect_false(result$is_current)

  # Clean up
  unlink(temp_pkg, recursive = TRUE)
})

test_that("gha_version.json manifest exists and is valid", {
  manifest_path <- system.file("gha_templates/gha_version.json", package = "gsm.utils")

  expect_true(file.exists(manifest_path))

  manifest <- jsonlite::fromJSON(manifest_path, simplifyVector = TRUE)

  expect_true("version" %in% names(manifest))
  expect_true("package" %in% names(manifest))
  expect_true("workflows" %in% names(manifest))
  expect_equal(manifest$package, "gsm.utils")
  expect_type(manifest$workflows, "list")
  expect_gt(length(manifest$workflows), 0)
})

test_that("all workflow templates have version headers", {
  workflows_dir <- system.file("gha_templates/workflows", package = "gsm.utils")
  workflow_files <- list.files(workflows_dir, pattern = "\\.ya?ml$", full.names = TRUE)

  expect_gt(length(workflow_files), 0)

  for (wf in workflow_files) {
    lines <- readLines(wf, n = 3, warn = FALSE)
    version_line <- grep("^# gsm.utils GHA version:", lines, value = TRUE)

    expect_equal(
      length(version_line),
      1,
      info = paste("File", basename(wf), "should have exactly one version header")
    )
  }
})

test_that("gha manifest workflow names match template files", {
  manifest_path <- system.file("gha_templates/gha_version.json", package = "gsm.utils")
  workflows_dir <- system.file("gha_templates/workflows", package = "gsm.utils")

  manifest <- jsonlite::fromJSON(manifest_path, simplifyVector = TRUE)
  expected_workflows <- sort(manifest$workflows$name)
  actual_workflows <- sort(list.files(workflows_dir, pattern = "\\.ya?ml$"))

  expect_setequal(
    expected_workflows,
    actual_workflows,
    info = "gha_version.json workflow entries must match files in inst/gha_templates/workflows"
  )
})
