name: "Build and deploy pkgdown site"
description: "Build and deploy a pkgdown site, including assets and PR-scoped sites."
inputs:
  # General
  repository_name:
    description: "Repository to which to deploy."
    required: false
    default: ${{ github.event.repository.name }}
  repository_owner:
    description: "Owner of the repository to which to deploy."
    required: false
    default: ${{ github.repository_owner }}
  token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
  event_name:
    description: "Type of event. Used to skip steps for non-PRs."
    required: false
    default: ${{ github.event_name}}
  pr_number:
    description: "Pull request number."
    required: false
    default: ${{ github.event.number }}
  root_dir:
    description: "Path to the root directory of the package, used to construct absolute paths."
    required: false
    default: .
  verbose:
    description: "Whether to print messages about rendered assets and menu updates."
    required: false
    default: false
  # pkgdown
  assets_dir:
    description: "Path to the directory where rendered `.html` files should be saved."
    required: false
    default: pkgdown/assets
  source_dir:
    description: "Path to the directory containing asset subdirectories."
    required: false
    default: pkgdown/menus
  pkgdown_dev_mode:
    description: "Pass 'devel' to operate in dev mode, leave blank or pass 'prod' otherwise."
    required: false
    default: ''
  pkgdown_yml:
    description: "Path to the `_pkgdown.yml` file to update with new menu items, or from which to remove unused menu items."
    required: false
    default: _pkgdown.yml

runs:
  using: "composite"
  steps:
    - name: Install R and dependencies
      uses: gilead-biostats/gsm.utils/.github/workflows/install@fix-67-render_menus
      with:
        token: ${{ inputs.token }}
        needs: website
        extra-packages: any::pkgdown gilead-biostats/qcthat local::.

    - name: Build pkgdown assets and add associated menus
      uses: gilead-biostats/gsm.utils/.github/workflows/pkgdown-build_assets@fix-67-render_menus
      with:
        assets_dir: ${{ inputs.assets_dir }}
        source_dir: ${{ inputs.source_dir }}
        pkgdown_yml: ${{ inputs.pkgdown_yml }}
        root_dir: ${{ inputs.root_dir }}
        verbose: ${{ inputs.verbose }}

    - name: Set Development Mode Env Var
      if: inputs.pkgdown_dev_mode == 'devel'
      shell: bash
      run: |
        echo "PKGDOWN_DEV_MODE=devel" >> $GITHUB_ENV

    - name: Build site
      env:
        GITHUB_PAT: ${{ inputs.token }}
      run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
      shell: Rscript {0}

    - name: Deploy PR preview 🧪
      uses: gilead-biostats/gsm.utils/.github/workflows/pkgdown-pr_preview@fix-67-render_menus
      with:
        repository_name: ${{ inputs.repository_name }}
        repository_owner: ${{ inputs.repository_owner }}
        token: ${{ inputs.token }}
        event_name: ${{ inputs.event_name }}
        pr_number: ${{ inputs.pr_number }}
        pkgdown_dev_mode: ${{ inputs.pkgdown_dev_mode }}

    - name: Deploy non-preview 📃
      if: inputs.event_name != 'pull_request'
      env:
        GITHUB_PAT: ${{ inputs.token }}
      shell: bash
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
