name: "Build and deploy pkgdown site"
description: "Build pkgdown assets, build the site, and deploy either as a PR preview or to the main branch."
inputs:
  # pkgdown-build_assets inputs
  assets-dir:
    description: "Path to the directory where rendered `.html` files should be saved."
    default: pkgdown/assets
  source-dir:
    description: "Path to the directory containing asset subdirectories."
    default: pkgdown/menus
  pkgdown-yml:
    description: "Path to the `_pkgdown.yml` file to update with new menu items, or from which to remove unused menu items."
    default: _pkgdown.yml
  root-dir:
    description: "Path to the root directory of the package, used to construct absolute paths."
    default: .
  verbose:
    description: "Whether to print messages about rendered assets and menu updates."
    default: false
  # pkgdown-pr_preview inputs
  repository-name:
    description: "Repository to which to deploy."
    default: ${{ github.event.repository.name }}
  repository-owner:
    description: "Owner of the repository to which to deploy."
    default: ${{ github.repository_owner }}
  token:
    description: "GitHub token, set to secrets.GITHUB_TOKEN"
    default: ${{ github.token }}
  event-name:
    description: "Type of event. Used to skip steps for non-PRs."
    default: ${{ github.event_name }}
  pr-number:
    description: "Pull request number."
    default: ${{ github.event.number }}
  is-fork:
    description: "Whether the PR is from a fork. Used to skip steps that require write permissions for forked PRs."
    default: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
  pkgdown-dev-mode:
    description: "Whether pkgdown should operate in dev mode."
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Build pkgdown assets and add associated menus
      uses: gilead-biostats/gsm.utils/pkgdown-build_assets@fix-97-configure_tokens
      with:
        assets-dir: ${{ inputs.assets-dir }}
        source-dir: ${{ inputs.source-dir }}
        pkgdown-yml: ${{ inputs.pkgdown-yml }}
        root-dir: ${{ inputs.root-dir }}
        verbose: ${{ inputs.verbose }}
    - name: Set Development Mode Env Var
      shell: bash
      run: |
        if [ "${{ inputs.pkgdown-dev-mode }}" == "true" ]; then
          echo "PKGDOWN_DEV_MODE=devel" >> $GITHUB_ENV
        fi
    - name: Build site
      run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
      shell: Rscript {0}
    - name: Deploy PR preview 🧪
      uses: gilead-biostats/gsm.utils/pkgdown-pr_preview@fix-97-configure_tokens
      with:
        repository-name: ${{ inputs.repository-name }}
        repository-owner: ${{ inputs.repository-owner }}
        token: ${{ inputs.token }}
        event-name: ${{ inputs.event-name }}
        pr-number: ${{ inputs.pr-number }}
        is-fork: ${{ inputs.is-fork }}
        pkgdown-dev-mode: ${{ inputs.pkgdown-dev-mode }}
    - name: Deploy non-preview 📃
      if: inputs.event-name != 'pull_request'
      shell: bash
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
