name: "Build pkgdown assets and add associated menus"
description: "Scan a directory for subdirectories, render any `.*md` files in those subdirectories to `.html`, and add them to the pkgdown index."
inputs:
  assets-dir:
    description: "Path to the directory where rendered `.html` files should be saved."
    default: pkgdown/assets
  source-dir:
    description: "Path to the directory containing asset subdirectories."
    default: pkgdown/menus
  pkgdown-yml:
    description: "Path to the `_pkgdown.yml` file to update with new menu items, or from which to remove unused menu items."
    default: _pkgdown.yml
  root-dir:
    description: "Path to the root directory of the package, used to construct absolute paths."
    default: .
  verbose:
    description: "Whether to print messages about rendered assets and menu updates."
    default: false
runs:
  using: "composite"
  steps:
    - env:
        SOURCE_DIR: ${{ inputs.source-dir }}
        ASSETS_DIR: ${{ inputs.assets-dir }}
        PKGDOWN_YML: ${{ inputs.pkgdown-yml }}
        ROOT_DIR: ${{ inputs.root-dir }}
        VERBOSE: ${{ inputs.verbose }}
      shell: Rscript {0}
      run: |
        gsm.utils::build_assets(
          source_dir = Sys.getenv("SOURCE_DIR", "pkgdown/menus"),
          assets_dir = Sys.getenv("ASSETS_DIR", "pkgdown/assets"),
          pkgdown_yml = Sys.getenv("PKGDOWN_YML", "_pkgdown.yml"),
          root_dir = Sys.getenv("ROOT_DIR", "."),
          verbose = isTRUE(as.logical(Sys.getenv("VERBOSE", "false")))
        )
