#' Check Workflow Template Compliance
#' 
#' @description
#' Checks if a package's GitHub Actions workflows comply with gsm.utils templates.
#' This function verifies file presence, version headers, and critical content.
#'
#' @param strPackageDir `character` path to package directory. Default is `"."`.
#' @param bVerbose `logical` whether to print detailed information. Default is `TRUE`.
#' @param bFailOnErrors `logical` whether to error if critical issues are found. Default is `TRUE`.
#'
#' @return A list with compliance check results:
#'   \item{is_compliant}{Logical indicating overall compliance}
#'   \item{missing_workflows}{Character vector of missing workflow files}
#'   \item{extra_workflows}{Character vector of extra workflow files not in templates}
#'   \item{version_issues}{Character vector of version/header issues}
#'   \item{content_issues}{Character vector of content differences}
#'   \item{gsm_utils_version}{Current gsm.utils version}
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Check current package compliance
#' check_workflow_compliance()
#' 
#' # Check another package
#' check_workflow_compliance("path/to/package")
#' }
check_workflow_compliance <- function(strPackageDir = ".", bVerbose = TRUE, bFailOnErrors = TRUE) {
  # Use check_gha_version() as foundation - it already handles manifest loading,
  # directory checks, and finding missing/extra workflows
  version_check <- check_gha_version(strPackageDir = strPackageDir, bVerbose = FALSE)
  
  if (bVerbose) {
    cli::cli_h1("GSM.utils Workflow Template Compliance Check")
    cli::cli_alert_info("GSM.utils template version: {version_check$gsm_utils_version}")
  }
  
  # If no workflows directory, return early
  workflows_dir <- file.path(strPackageDir, ".github", "workflows")
  if (!dir.exists(workflows_dir)) {
    if (bVerbose) {
      cli::cli_alert_danger("No .github/workflows directory found!")
      cli::cli_alert_info("This package should have GitHub Actions workflows matching gsm.utils templates.")
    }
    result <- list(
      is_compliant = FALSE,
      missing_workflows = version_check$workflows_missing,
      extra_workflows = character(0),
      version_issues = character(0),
      content_issues = character(0),
      gsm_utils_version = version_check$gsm_utils_version
    )
    if (bFailOnErrors) {
      cli::cli_abort("No {.path .github/workflows} directory found in {.path {strPackageDir}}.")
    }
    return(result)
  }
  
  # Get workflow information from version check
  missing_workflows <- version_check$workflows_missing
  expected_workflows <- c(version_check$workflows_found, version_check$workflows_missing)
  existing_workflows <- list.files(workflows_dir, pattern = "\\.ya?ml$")
  extra_workflows <- setdiff(existing_workflows, expected_workflows)
  
  if (bVerbose) {
    cli::cli_alert_info("Expected workflow files: {paste(expected_workflows, collapse = ', ')}")
    cli::cli_alert_info("Found workflow files: {paste(existing_workflows, collapse = ', ')}")
  }
  
  # Check version headers and content (beyond what check_gha_version provides)
  version_issues <- check_workflow_headers(workflows_dir, existing_workflows, expected_workflows, version_check$gsm_utils_version)
  content_issues <- check_critical_workflow_content(workflows_dir, existing_workflows)
  
  # Determine if there are critical errors
  has_errors <- length(missing_workflows) > 0 || length(version_issues) > 0
  
  # Report findings
  if (bVerbose) {
    report_compliance_results(missing_workflows, extra_workflows, version_issues, content_issues, has_errors)
  }
  
  # Exit with error if requested and issues found
  if (bFailOnErrors && has_errors) {
    cli::cli_abort("Workflow compliance issues found.")
  }
  
  return(list(
    is_compliant = !has_errors,
    missing_workflows = missing_workflows,
    extra_workflows = extra_workflows,
    version_issues = version_issues,
    content_issues = content_issues,
    gsm_utils_version = version_check$gsm_utils_version
  ))
}

#' @noRd
check_workflow_headers <- function(workflows_dir, existing_workflows, expected_workflows, gsm_utils_version) {
  version_issues <- character(0)
  
  for (wf in intersect(existing_workflows, expected_workflows)) {
    workflow_path <- file.path(workflows_dir, wf)
    if (!file.exists(workflow_path)) next
    
    lines <- readLines(workflow_path, n = 5, warn = FALSE)
    
    # Check for version header
    version_line <- grep("^# gsm.utils GHA version:", lines, value = TRUE)
    if (length(version_line) == 0) {
      version_issues <- c(version_issues, paste0(wf, ": Missing version header"))
    } else {
      # Extract and validate version
      file_version <- sub("^# gsm.utils GHA version:\\s*", "", version_line[1])
      if (file_version != gsm_utils_version) {
        version_issues <- c(version_issues, paste0(wf, ": Version ", file_version, " (expected ", gsm_utils_version, ")"))
      }
    }
    
    # Check for generated by header
    if (!any(grepl("^# Generated by:", lines))) {
      version_issues <- c(version_issues, paste0(wf, ": Missing \"Generated by\" header"))
    }
  }
  
  version_issues
}

#' @noRd
check_critical_workflow_content <- function(workflows_dir, existing_workflows) {
  critical_workflows <- c("R-CMD-check.yaml", "R-CMD-check-dev.yaml")
  content_issues <- character(0)
  
  for (wf in intersect(existing_workflows, critical_workflows)) {
    workflow_path <- file.path(workflows_dir, wf)
    template_path <- system.file("gha_templates/workflows", wf, package = "gsm.utils")

    # Development fallback (only works when run from gsm.utils repo root)
    if ((is.na(template_path) || template_path == "" || !file.exists(template_path)) &&
        file.exists(file.path("inst", "gha_templates", "workflows", wf))) {
      template_path <- file.path("inst", "gha_templates", "workflows", wf)
    }
    
    if (!file.exists(template_path)) next
    
    template_content <- readLines(template_path, warn = FALSE)
    workflow_content <- readLines(workflow_path, warn = FALSE)
    
    # Compare key sections (excluding comment lines)
    template_clean <- template_content[!grepl("^#", template_content)]
    workflow_clean <- workflow_content[!grepl("^#", workflow_content)]
    
    if (!identical(template_clean, workflow_clean)) {
      content_issues <- c(content_issues, paste0(wf, ": Content differs from template"))
    }
  }
  
  content_issues
}

#' @noRd
report_compliance_results <- function(missing_workflows, extra_workflows, version_issues, content_issues, has_errors) {
  if (length(missing_workflows) > 0) {
    cli::cli_alert_danger("Missing required workflow files:")
    for (wf in missing_workflows) cli::cli_alert_danger("  - {wf}")
  }
  
  if (length(extra_workflows) > 0) {
    cli::cli_alert_warning("Extra workflow files (not in gsm.utils templates):")
    for (wf in extra_workflows) cli::cli_alert_warning("  - {wf}")
  }
  
  if (length(version_issues) > 0) {
    cli::cli_alert_danger("Workflow version/header issues:")
    for (issue in version_issues) cli::cli_alert_danger("  - {issue}")
  }
  
  if (length(content_issues) > 0) {
    cli::cli_alert_warning("Workflow content differences (may be acceptable):")
    for (issue in content_issues) cli::cli_alert_warning("  - {issue}")
  }
  
  # Summary
  if (!has_errors) {
    if (length(version_issues) == 0 && length(missing_workflows) == 0) {
      cli::cli_alert_success("All workflow files are compliant with gsm.utils templates!")
    } else {
      cli::cli_alert_success("No critical issues found")
    }
  } else {
    cli::cli_alert_danger("Workflow compliance issues found!")
    cli::cli_alert_info("To fix these issues, run: gsm.utils::update_gsm_package()")
  }
}