# name: pkgdown-core.yaml
# version: 0.4.2
# Description: Reusable workflow to deploy pkgdown site with assets and clean up PR previews.
name: pkgdown-core
on:
  workflow_call:
    inputs:
      mode:
        description: "Mode to run: deploy or cleanup"
        default: 'deploy'
        type: string
      pr-number:
        description: "Pull request number. Leave blank to deploy to a branch."
        type: string
      pkgdown-dev-mode:
        description: "Whether pkgdown should operate in dev mode."
        type: boolean
        default: false
      utils-ref:
        description: "Ref for gsm.utils to install"
        type: string
        default: '@*release'
    secrets:
      token:
        description: "GitHub token, set to secrets.GITHUB_TOKEN"
        required: false
      app-id:
        required: false
      app-private-key:
        required: false
jobs:
  pkgdown-assets:
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.action != 'closed') ||
      (github.event_name == 'workflow_dispatch' && inputs.mode == 'deploy')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate token
        uses: gilead-biostats/gsm.utils/generate-token@fix-bash-runner
        id: token
        with:
          app-id: ${{ secrets.app-id }}
          app-private-key: ${{ secrets.app-private-key }}
          owner: ${{ github.repository_owner }}
          fallback-token: ${{ secrets.token || github.token }}
      - name: Set GITHUB_PAT
        shell: bash
        run: echo "GITHUB_PAT=${{ steps.token.outputs.token }}" >> $GITHUB_ENV
      - name: Determine checkout ref
        id: get-ref
        if: github.event_name == 'workflow_dispatch'
        uses: gilead-biostats/gsm.utils/determine-ref@fix-bash-runner
        with:
          pr-number: ${{ inputs.pr-number }}
          token: ${{ steps.token.outputs.token }}
      - name: Check out repo
        uses: gilead-biostats/gsm.utils/checkout@fix-bash-runner
        with:
          token: ${{ steps.token.outputs.token }}
          ref: ${{ steps.get-ref.outputs.ref }}
      - name: Install R and dependencies
        uses: gilead-biostats/gsm.utils/install@fix-bash-runner
        with:
          token: ${{ steps.token.outputs.token }}
          r-version: release
          needs: website
          extra-packages: any::pkgdown gilead-biostats/gsm.utils${{ inputs.utils-ref }} local::.
          cache-version: '1'
      - name: Build and deploy site
        uses: gilead-biostats/gsm.utils/pkgdown-deploy@fix-bash-runner
        with:
          token: ${{ steps.token.outputs.token }}
          event-name: ${{ inputs.pr-number && 'pull_request' || github.event_name }}
          pr-number: ${{ inputs.pr-number || github.event.number }}
          pkgdown-dev-mode: ${{ inputs.pkgdown-dev-mode == true || (github.event_name != 'workflow_dispatch' && github.ref_name != 'main') }}
          is-fork: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
  clean-pr-preview:
    if: |
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.head.repo.full_name == github.repository) ||
      (github.event_name == 'workflow_dispatch' && inputs.mode == 'cleanup')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate token
        uses: gilead-biostats/gsm.utils/generate-token@fix-bash-runner
        id: token
        with:
          app-id: ${{ secrets.app-id }}
          app-private-key: ${{ secrets.app-private-key }}
          owner: ${{ github.repository_owner }}
          fallback-token: ${{ secrets.token || github.token }}
      - name: Clean up PR preview
        uses: gilead-biostats/gsm.utils/pkgdown-cleanup@fix-bash-runner
        with:
          token: ${{ steps.token.outputs.token }}
          pr-number: ${{ inputs.pr-number || github.event.number }}
