# name: r-releaser.yaml
# version: 0.4.2
# Description: Reusable R package release workflow designed to be invoked by
# other gsm packages via r-releaser-caller.yaml workflow
name: R Release
on:
  workflow_call:
    inputs:
      tag:
        description: Tag to release
        required: true
        type: string
    secrets:
      token:
        description: "GitHub token, set to secrets.GITHUB_TOKEN"
        required: false
      app-id:
        required: false
      app-private-key:
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate token
        uses: gilead-biostats/gsm.utils/generate-token@fix-bash-runner
        id: token
        with:
          app-id: ${{ secrets.app-id }}
          app-private-key: ${{ secrets.app-private-key }}
          owner: ${{ github.repository_owner }}
          fallback-token: ${{ secrets.token || github.token }}
      - name: Set GITHUB_PAT
        shell: bash
        run: echo "GITHUB_PAT=${{ steps.token.outputs.token }}" >> $GITHUB_ENV
      - name: Check out repo
        uses: gilead-biostats/gsm.utils/checkout@fix-bash-runner
        with:
          token: ${{ steps.token.outputs.token }}
          fetch-depth: 0
      - name: Install R and dependencies
        uses: gilead-biostats/gsm.utils/install@fix-bash-runner
        with:
          use-public-rspm: true
          token: ${{ steps.token.outputs.token }}
      - name: get library path
        id: library
        shell: bash
        run: |
          OUTPUT=$(Rscript -e "cat(.libPaths()[1])")
          echo "result=$OUTPUT" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
      - name: Run R Releaser
        id: releaser
        uses: A2-ai/r-releaser/build-src@main
        with:
          library: ${{ steps.library.outputs.result }}
          resave-data: false
          md5: true
          build-vignettes: false
      - name: echo output
        shell: bash
        run: |
          echo ${{ steps.releaser.outputs.tarball_path }}
          echo ${{ steps.releaser.outputs.tarball_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ steps.token.outputs.token }}
          file: ${{ steps.releaser.outputs.tarball_path }}
          asset_name: ${{ steps.releaser.outputs.tarball_name }}
          tag: ${{ inputs.tag }}
          overwrite: true
