on:
  pull_request:
  workflow_dispatch:

name: utils-version

jobs:
  pkgdown-assets:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Install R and dependencies
        uses: gilead-biostats/gsm.utils/actions/install@actions-v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          needs: website
          extra-packages: gilead-biostats/gsm.utils@actions-v1 local::.

      - name: Check gsm.utils version
        run: packageVersion("gsm.utils")
        shell: Rscript {0}
