# name: test-coverage-core.yaml
# version: 0.3.7
# Description: Reusable workflow to compute test coverage and publish coverage-summary.json artifact

name: test-coverage-core

on:
  workflow_call:
    secrets:
      token:
        description: "GitHub token, set to secrets.GITHUB_TOKEN"
        required: false

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Compute test coverage
        uses: gilead-biostats/gsm.utils/coverage@actions-v1
        with:
          token: ${{ secrets.token || github.token }}
