# name: test-coverage-core.yaml
# version: 0.4.0
# Description: Reusable workflow to compute test coverage and publish coverage-summary.json artifact

name: test-coverage-core

on:
  workflow_call:
    secrets:
      token:
        description: "GitHub token, set to secrets.GITHUB_TOKEN"
        required: false
      app-id:
        required: false
      app-private-key:
        required: false

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate token
        uses: gilead-biostats/gsm.utils/generate-token@fix-130-app-tokens
        id: token
        with:
          app-id: ${{ secrets.app-id }}
          app-private-key: ${{ secrets.app-private-key }}
          owner: ${{ github.repository_owner }}
          fallback-token: ${{ secrets.token || github.token }}
      - name: Compute test coverage
        uses: gilead-biostats/gsm.utils/coverage@actions-v1
        with:
          token: ${{ steps.token.outputs.token }}
