# name: test-coverage-core.yaml
# version: 0.3.6
# Description: Reusable workflow to compute test coverage and publish coverage-summary.json artifact

name: test-coverage-core

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Compute test coverage
        uses: gilead-biostats/gsm.utils/coverage@fix-78-comment-pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
